# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixloglikC <- function(data, means, covmat, b, c) {
    .Call('grtools_matrixloglikC', PACKAGE = 'grtools', data, means, covmat, b, c)
}

